[book]
authors = ["Nik Revenco"]
language = "en"
title = "Peashot"

[output.html]
site-url = "/docs/"
preferred-dark-theme = "peashot"
default-theme = "peashot"
git-repository-url = "https://github.com/nik-rev/peashot"
edit-url-template = "https://github.com/nik-rev/peashot/edit/main/docs/{path}"
additional-css = ["theme/fonts/fonts.css", "theme/extra.css", "theme/noise.png"]
# Don't show table of contents for entire page in the navigation bar
sidebar-header-nav = false
no-section-label = true
hash-files = false
