# name: GitHub Pages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Build mdbook
#         run: |
#           mkdir bin
#           # fetch mdbook binary
#           curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.48/mdbook-v0.4.48-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
#           # we want our `./index.html` which is the landing page at the root and served at `ferrishot.com` root
#           # And `./book/index.html` will be served at `ferrishot.com/docs`
#           bin/mdbook build docs
#           mv docs docs-src
#           mv docs-src/docs .

#       - name: Setup Pages
#         uses: actions/configure-pages@v4

#       - name: Upload GitHub Pages artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: .

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     permissions:
#       pages: write
#       id-token: write # required for OIDC in deploy-pages action
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
